### ISSUE TITLE
Multiple output files

### ISSUE THREAD

**Issue by karneaud** [RobLoach/metalsmith-concat-convention#1]
Does this mean I can have more than one .concat to handle more than one output file?

thus

src/
--script1.js.concat
--script2.js.concat

outputs

js/
--script1.js
--script2.js

?

**Comment by RobLoach** [comment]
Yup! Can have multiple concatinated files. See the test for an example:
https://github.com/RobLoach/metalsmith-concat-convention/tree/master/test/fixtures/multiple/src
