### ISSUE TITLE
Glob support

### ISSUE THREAD

**Issue by rstacruz** [RobLoach/metalsmith-concat-convention#3]
It'd be nice to have support for this.

```yaml
---
files:
  - base/*.css
  - components/*.css
  - helpers/*.css
---
```

**Comment by rstacruz** [comment]
oh wait, you already can!

**Comment by RobLoach** [comment]
Can you??????

**Comment by rstacruz** [comment]
YES I CAN AND NO ONE CAN STOP ME

Metalsmith-concat already supports globs, so by extension this should too.
