### ISSUE TITLE
default output folder

### ISSUE THREAD

**Issue by fparaggio** [RobLoach/metalsmith-concat-convention#4]
It seems that the plugin default output folder is the destination one. It does not inherit the starting folder.
Is it the expected behavior? 

How can I leave the output files in the same folder where the plugin find them?

**Comment by fparaggio** [comment]
ok, i solved specifying 
```
output: path/custom.js
```
in the files:. It would be great if is it possible to specify something like "inplace: true" in the plugin config.

**Comment by RobLoach** [comment]
Seems like a bug... Added a test for this: https://github.com/RobLoach/metalsmith-concat-convention/pull/5 ... Mind checking it out and seeing what's missing? May be something that we need to push upstream.
